### PR TITLE
errors: lower enum size from 120 bytes to 80

### LINKED ISSUE #558: `pgp::errors::Error` is very big
Hi,

We're using rpgp-0.16-alpha.1 and found out that embedding `prpg::errors::Error` triggers the [`clippy::result-large-err`](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err) lint:

```
error: the `Err`-variant returned from this function is very large
   --> nethsm/src/openpgp.rs:551:23
    |
551 | pub fn sign_mode() -> pgp::errors::Result<crate::SignatureType> {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 128 bytes
    |
    = help: try reducing the size of `pgp::errors::Error`, for example by boxing large elements or replacing it with `Box<pgp::errors::Error>`
```

Running diagnostics via `RUSTFLAGS=-Zprint-type-sizes cargo +nightly build --release` reveals that the enum has 128 bytes, which is sufficient to trigger the lint if it's embedded in another enum.

The breakdown of sizes for variants is the following:

```
type: `pgp::errors::Error`: 128 bytes, alignment: 8 bytes
    discriminant: 1 bytes
    variant `RSAError`: 127 bytes
        padding: 7 bytes
        field `.source`: 72 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `PacketParsing`: 127 bytes
        padding: 7 bytes
        field `.source`: 120 bytes, alignment: 8 bytes
    variant `PacketIncomplete`: 127 bytes
        padding: 7 bytes
        field `.source`: 120 bytes, alignment: 8 bytes
    variant `Unimplemented`: 79 bytes
        padding: 7 bytes
        field `.message`: 24 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `Unsupported`: 79 bytes
        padding: 7 bytes
        field `.message`: 24 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `Message`: 79 bytes
        padding: 7 bytes
        field `.message`: 24 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `Base64Decode`: 71 bytes
        padding: 7 bytes
        field `.source`: 16 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `Utf8Error`: 71 bytes
        padding: 7 bytes
        field `.source`: 16 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `IO`: 63 bytes
        padding: 7 bytes
        field `.source`: 8 bytes, alignment: 8 bytes
        field `.backtrace`: 48 bytes
    variant `InvalidInput`: 55 bytes
        padding: 7 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `NoMatchingPacket`: 55 bytes
        padding: 7 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `EllipticCurve`: 55 bytes
        field `.source`: 0 bytes
        padding: 7 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `ParseIntError`: 55 bytes
        field `.source`: 1 bytes
        padding: 6 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `TryFromInt`: 55 bytes
        field `.source`: 0 bytes
        padding: 7 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `Argon2`: 55 bytes
        field `.source`: 1 bytes
        padding: 6 bytes
        field `.backtrace`: 48 bytes, alignment: 8 bytes
    variant `AesKw`: 31 bytes
        padding: 7 bytes
        field `.source`: 24 bytes, alignment: 8 bytes
    variant `SignatureError`: 23 bytes
        padding: 7 bytes
        field `.source`: 16 bytes, alignment: 8 bytes
    variant `Aead`: 23 bytes
        padding: 7 bytes
        field `.source`: 16 bytes, alignment: 8 bytes
    variant `AesKek`: 23 bytes
        padding: 7 bytes
        field `.source`: 16 bytes, alignment: 8 bytes
    variant `PacketTooLarge`: 15 bytes
        padding: 7 bytes
        field `.size`: 8 bytes, alignment: 8 bytes
    variant `InvalidPacketContent`: 15 bytes
        padding: 7 bytes
        field `.source`: 8 bytes, alignment: 8 bytes
    variant `ChecksumMissmatch`: 4 bytes
        field `.source`: 4 bytes
    variant `PacketError`: 1 bytes
        field `.kind`: 1 bytes
    variant `SigningError`: 1 bytes
        field `.source`: 1 bytes
    variant `InvalidArmorWrappers`: 0 bytes
    variant `InvalidChecksum`: 0 bytes
    variant `RequestedSizeTooLarge`: 0 bytes
    variant `TooManyPackets`: 0 bytes
    variant `InvalidKeyLength`: 0 bytes
    variant `BlockMode`: 0 bytes
    variant `MissingKey`: 0 bytes
    variant `CfbInvalidKeyIvLength`: 0 bytes
    variant `UnpadError`: 0 bytes
    variant `PadError`: 0 bytes
    variant `MdcError`: 0 bytes
    variant `Sha1HashCollision`: 0 bytes
        field `.source`: 0 bytes
```

On our end we Boxed the value but boxing everything in helper functions returning `pgp::errors::Result` gets pretty messy.

I think it'd be a good idea to internally box the variants that are using large amount of space but any other solution to this problem would be greatly appreciated 🙏

### PR DESCRIPTION
**Pull request by baloo**
This lowers the size of the Error enum from 120 bytes to 80 bytes to steer away from the limit checked by clippy (128 bytes): https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err

Fixes #558

### CODE REVIEW

**Comment by hko-s** [comment]
You might rebase the PR on main, though!

File: src/errors.rs [hunk 1]
```diff
@@ -293,3 +294,21 @@ pub(crate) use err_opt;
...
+    /// size of the `Error` enum lower than that limit with some headroom to be wrapped by a
+    /// downstream crate.
+    ///
+    /// If this test triggers, you should consider Box'ing the offending member.
+    ///
+    /// See: <https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err>
+    #[cfg(target_pointer_width = "64")]
+    #[test]
+    fn size_of_error() {
+        assert_eq!(core::mem::size_of::<super::Error>(), 80);
```
Comment (wiktor-k) [inline src/errors.rs:312]: I wonder if this shouldn't be something like:

```suggestion
        assert!(core::mem::size_of::<super::Error>() <= 80, "Error needs a diet!");
```

That is if the error is smaller than 80 we don't care about the exact value. (The error message is just a sample :wink: )

File: src/errors.rs [hunk 2]
```diff
@@ -293,3 +294,21 @@ pub(crate) use err_opt;
...
+    /// Because clippy will start throwing warning if an enum gets above 128, we'd like to keep the
+    /// size of the `Error` enum lower than that limit with some headroom to be wrapped by a
+    /// downstream crate.
+    ///
+    /// If this test triggers, you should consider Box'ing the offending member.
+    ///
+    /// See: <https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err>
+    #[cfg(target_pointer_width = "64")]
+    #[test]
+    fn size_of_error() {
```
Comment (wiktor-k) [inline src/errors.rs:311]:
```suggestion
    fn error_is_not_too_big() {
```

:thinking:

**Comment by wiktor-k** [comment]
Yeah, I think this is a worthwhile addition and if possible it'd be good to get that merged before the final release :pray:

File: src/errors.rs (hunk 1 above)
Comment (hko-s) [reply src/errors.rs:312]: @wiktor-k Sorry, race condition :scream: 

... let's do these changes once the test complains, in the future ;)

Comment (wiktor-k) [reply src/errors.rs:312]: Oh, that's a good idea too! Also it doesn't seem like it would go down by accident given the amount of variants there. Okay, thanks! :wave:
